### ISSUE TITLE
How to move your body

### ISSUE THREAD

**Issue by datased2019** [maceq687/FullBodyPoseEstimation#1]
Hi. Great job. Very clear. But it seems we cannot move around, near or far. Any comment? Thx.

**Comment by maceq687** [comment]
You should be able to move. Which scene are you experiencing this problem in? Are you working with Quest 2 as HMD?

**Comment by datased2019** [comment]
@maceq687  Sorry I didn't make it clear. I am just using BlazePose without Quest. So if I want to move my body I should use Quest as HMD, right?

**Comment by maceq687** [comment]
Yes, this project is designed specifically to make full body pose estimation work with Quest

**Comment by datased2019** [comment]
Thx for your quick reply.
