### ISSUE TITLE
i can not open the unity project

### ISSUE THREAD

**Issue by DanceWithFeathers** [maceq687/FullBodyPoseEstimation#3]
Could not create asset from Assets/Polytope Studio/Lowpoly Medieval Characters/Sources/Modular_Armors/Textures/PT_Medieval_Armors_Base_Texture<img width="1044" alt="屏幕截图 2024-01-07 120858" src="https://github.com/maceq687/FullBodyPoseEstimation/assets/73521658/d56576d7-7685-4b24-9abb-9b4f2fac8f93">

**Comment by DanceWithFeathers** [comment]
i use the same unity version which is 2019.4.28f1, but it still does not work

**Comment by DanceWithFeathers** [comment]
I have used my whole day trying to run "PoseScene".  when I first open this project, it shows that "Rebuilding Library because the asset database could not be found!" followed by many errors which show the project may not import things well.

**Comment by maceq687** [comment]
From the screenshot I can see that you are missing some .png and .tif files so perhaps it is an issue caused by missing Git LFS files in the project.  
If this is the case you can try running `git lfs pull` in your projects repository to try to resolve that.

**Comment by DanceWithFeathers** [comment]
Thanks a lot! I think that is the reason. I uesd `git lfs clone` to pull the whole project again and it works well now. 
the reason why it showed error is that i just downloaded  Zip file and unziped it. :(
